[package]
name = "radarweb"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.78"
copyless = "0.1.5"
wee_alloc = "0.4.5"
pokeradar = {path = "../pokeradar"}
